// Centralized locations data: countries and country-to-cities mapping

export const countryToCities = {
  Pakistan: [
    'Islamabad', 'Ahmed Nager', 'Ahmadpur East', 'Ali Khan', 'Alipur', 'Arifwala', 'Attock', 'Bhera', 'Bhalwal', 'Bahawalnagar', 'Bahawalpur', 'Bhakkar', 'Burewala', 'Chillianwala', 'Chak', 'Chakwal', 'Chichawatni', 'Chiniot', 'Chishtian', 'Daska', 'Darya Khan', 'Dera Ghazi', 'Dhaular', 'Dina', 'Dinga', 'Dipalpur', 'Faisalabad', 'Fateh Jhang', 'Ghakhar Mandi', 'Gojra', 'Gujranwala', 'Gujrat', 'Gujar Khan', 'Hafizabad', 'Haroonabad', 'Hasilpur', 'Haveli', 'Lakha', 'Jalalpur', 'Jattan', 'Jampur', 'Jaranwala', 'Jhang', 'Jhelum', 'Kalabagh', 'Karor Lal', 'Kasur', 'Kamalia', 'Kamoke', 'Khanewal', 'Khanpur', 'Kharian', 'Khushab', 'Kot Adu', 'Jauharabad', 'Lahore', 'Lalamusa', 'Layyah', 'Liaquat Pur', 'Lodhran', 'Malakwal', 'Mamoori', 'Mailsi', 'Mandi Bahauddin', 'mian Channu', 'Mianwali', 'Multan', 'Murree', 'Muridke', 'Mianwali Bangla', 'Muzaffargarh', 'Narowal', 'Okara', 'Renala Khurd', 'Pakpattan', 'Pattoki', 'Pir Mahal', 'Qaimpur', 'Qila Didar', 'Rabwah', 'Raiwind', 'Rajanpur', 'Rahim Yar', 'Rawalpindi', 'Sadiqabad', 'Safdarabad', 'Sahiwal', 'Sangla Hill', 'Sarai Alamgir', 'Sargodha', 'Shakargarh', 'Sheikhupura', 'Sialkot', 'Sohawa', 'Soianwala', 'Siranwali', 'Talagang', 'Taxila', 'Toba Tek', 'Vehari', 'Wah Cantonment', 'Wazirabad', 'Badin', 'Bhirkan', 'Rajo Khanani', 'Dadu', 'Digri', 'Diplo', 'Dokri', 'Ghotki', 'Haala', 'Hyderabad', 'Islamkot', 'Jacobabad', 'Jamshoro', 'Jungshahi', 'Kandhkot', 'Kandiaro', 'Karachi', 'Kashmore', 'Keti Bandar', 'Khairpur', 'Kotri', 'Larkana', 'Matiari', 'Mehar', 'Mirpur Khas', 'Mithani', 'Mithi', 'Mehrabpur', 'Moro', 'Nagarparkar', 'Naudero', 'Naushahro Feroze', 'Naushara', 'Nawabshah', 'Nazimabad', 'Qambar', 'Qasimabad', 'Ranipur', 'Ratodero', 'Rohri', 'Sakrand', 'Sanghar', 'Shahbandar', 'Shahdadkot', 'Shahdadpur', 'Shahpur Chakar', 'Shikarpaur', 'Sukkur', 'Tangwani', 'Tando Adam', 'Tando Allahyar', 'Tando Muhammad', 'Thatta', 'Umerkot', 'Warah', 'Abbottabad', 'Adezai', 'Alpuri', 'Akora Khattak', 'Ayubia', 'Banda Daud', 'Bannu', 'Batkhela', 'Battagram', 'Birote', 'Chakdara', 'Charsadda', 'Chitral', 'Daggar', 'Dargai', 'dera Ismail', 'Doaba', 'Dir', 'Drosh', 'Hangu', 'Haripur', 'Karak', 'Kohat', 'Kulachi', 'Lakki Marwat', 'Latamber', 'Madyan', 'Mansehra', 'Mardan', 'Mastuj', 'Mingora', 'Nowshera', 'Paharpur', 'Pabbi', 'Peshawar', 'Saidu Sharif', 'Shorkot', 'Shewa Adda', 'Swabi', 'Swat', 'Tangi', 'Tank', 'Thall', 'Timergara', 'Tordher', 'Awaran', 'Barkhan', 'Chagai', 'Dera Bugti', 'Gwadar', 'Harnai', 'Jafarabad', 'Jhal Magsi', 'Kacchi', 'Kalat', 'Kech', 'Kharan', 'Khuzdar', 'Killa Abdullah', 'Killa Saifullah', 'Kohlu', 'Lasbela', 'Lehri', 'Loralai', 'Mastung', 'Musakhel', 'Nasirabad', 'Nushki', 'Panjgur', 'Pishin valley', 'Quetta', 'Sherani', 'Sibi', 'Sohbatpur', 'Washuk', 'Zhob', 'Ziarat'
  ],
  India: ['Delhi', 'Mumbai', 'Bengaluru', 'Hyderabad', 'Chennai', 'Kolkata'],
  USA: ['New York', 'Los Angeles', 'Chicago', 'Houston', 'San Francisco', 'Seattle'],
  UK: ['London', 'Manchester', 'Birmingham', 'Leeds', 'Glasgow', 'Liverpool'],
};

export const countryList = [
	"Afghanistan",
	"Albania",
	"Algeria",
	"American Samoa",
	"Andorra",
	"Angola",
	"Anguilla",
	"Antarctica",
	"Antigua and Barbuda",
	"Argentina",
	"Armenia",
	"Aruba",
	"Australia",
	"Austria",
	"Azerbaijan",
	"Bahamas (the)",
	"Bahrain",
	"Bangladesh",
	"Barbados",
	"Belarus",
	"Belgium",
	"Belize",
	"Benin",
	"Bermuda",
	"Bhutan",
	"Bolivia (Plurinational State of)",
	"Bonaire, Sint Eustatius and Saba",
	"Bosnia and Herzegovina",
	"Botswana",
	"Bouvet Island",
	"Brazil",
	"British Indian Ocean Territory (the)",
	"Brunei Darussalam",
	"Bulgaria",
	"Burkina Faso",
	"Burundi",
	"Cabo Verde",
	"Cambodia",
	"Cameroon",
	"Canada",
	"Cayman Islands (the)",
	"Central African Republic (the)",
	"Chad",
	"Chile",
	"China",
	"Christmas Island",
	"Cocos (Keeling) Islands (the)",
	"Colombia",
	"Comoros (the)",
	"Congo (the Democratic Republic of the)",
	"Congo (the)",
	"Cook Islands (the)",
	"Costa Rica",
	"Croatia",
	"Cuba",
	"Curaçao",
	"Cyprus",
	"Czechia",
	"Côte d'Ivoire",
	"Denmark",
	"Djibouti",
	"Dominica",
	"Dominican Republic (the)",
	"Ecuador",
	"Egypt",
	"El Salvador",
	"Equatorial Guinea",
	"Eritrea",
	"Estonia",
	"Eswatini",
	"Ethiopia",
	"Falkland Islands (the) [Malvinas]",
	"Faroe Islands (the)",
	"Fiji",
	"Finland",
	"France",
	"French Guiana",
	"French Polynesia",
	"French Southern Territories (the)",
	"Gabon",
	"Gambia (the)",
	"Georgia",
	"Germany",
	"Ghana",
	"Gibraltar",
	"Greece",
	"Greenland",
	"Grenada",
	"Guadeloupe",
	"Guam",
	"Guatemala",
	"Guernsey",
	"Guinea",
	"Guinea-Bissau",
	"Guyana",
	"Haiti",
	"Heard Island and McDonald Islands",
	"Holy See (the)",
	"Honduras",
	"Hong Kong",
	"Hungary",
	"Iceland",
	"India",
	"Indonesia",
	"Iran (Islamic Republic of)",
	"Iraq",
	"Ireland",
	"Isle of Man",
	"Israel",
	"Italy",
	"Jamaica",
	"Japan",
	"Jersey",
	"Jordan",
	"Kazakhstan",
	"Kenya",
	"Kiribati",
	"Korea (the Democratic People's Republic of)",
	"Korea (the Republic of)",
	"Kuwait",
	"Kyrgyzstan",
	"Lao People's Democratic Republic (the)",
	"Latvia",
	"Lebanon",
	"Lesotho",
	"Liberia",
	"Libya",
	"Liechtenstein",
	"Lithuania",
	"Luxembourg",
	"Macao",
	"Madagascar",
	"Malawi",
	"Malaysia",
	"Maldives",
	"Mali",
	"Malta",
	"Marshall Islands (the)",
	"Martinique",
	"Mauritania",
	"Mauritius",
	"Mayotte",
	"Mexico",
	"Micronesia (Federated States of)",
	"Moldova (the Republic of)",
	"Monaco",
	"Mongolia",
	"Montenegro",
	"Montserrat",
	"Morocco",
	"Mozambique",
	"Myanmar",
	"Namibia",
	"Nauru",
	"Nepal",
	"Netherlands (the)",
	"New Caledonia",
	"New Zealand",
	"Nicaragua",
	"Niger (the)",
	"Nigeria",
	"Niue",
	"Norfolk Island",
	"Northern Mariana Islands (the)",
	"Norway",
	"Oman",
	"Pakistan",
	"Palau",
	"Palestine, State of",
	"Panama",
	"Papua New Guinea",
	"Paraguay",
	"Peru",
	"Philippines (the)",
	"Pitcairn",
	"Poland",
	"Portugal",
	"Puerto Rico",
	"Qatar",
	"Republic of North Macedonia",
	"Romania",
	"Russian Federation (the)",
	"Rwanda",
	"Réunion",
	"Saint Barthélemy",
	"Saint Helena, Ascension and Tristan da Cunha",
	"Saint Kitts and Nevis",
	"Saint Lucia",
	"Saint Martin (French part)",
	"Saint Pierre and Miquelon",
	"Saint Vincent and the Grenadines",
	"Samoa",
	"San Marino",
	"Sao Tome and Principe",
	"Saudi Arabia",
	"Senegal",
	"Serbia",
	"Seychelles",
	"Sierra Leone",
	"Singapore",
	"Sint Maarten (Dutch part)",
	"Slovakia",
	"Slovenia",
	"Solomon Islands",
	"Somalia",
	"South Africa",
	"South Georgia and the South Sandwich Islands",
	"South Sudan",
	"Spain",
	"Sri Lanka",
	"Sudan (the)",
	"Suriname",
	"Svalbard and Jan Mayen",
	"Sweden",
	"Switzerland",
	"Syrian Arab Republic",
	"Taiwan",
	"Tajikistan",
	"Tanzania, United Republic of",
	"Thailand",
	"Timor-Leste",
	"Togo",
	"Tokelau",
	"Tonga",
	"Trinidad and Tobago",
	"Tunisia",
	"Turkey",
	"Turkmenistan",
	"Turks and Caicos Islands (the)",
	"Tuvalu",
	"Uganda",
	"Ukraine",
	"United Arab Emirates (the)",
	"United Kingdom of Great Britain and Northern Ireland (the)",
	"United States Minor Outlying Islands (the)",
	"United States of America (the)",
	"Uruguay",
	"Uzbekistan",
	"Vanuatu",
	"Venezuela (Bolivarian Republic of)",
	"Viet Nam",
	"Virgin Islands (British)",
	"Virgin Islands (U.S.)",
	"Wallis and Futuna",
	"Western Sahara",
	"Yemen",
	"Zambia",
	"Zimbabwe",
	"Åland Islands"
];

// Provide helpers used across components
export const getCities = (country) => countryToCities[country] || [];
export const isCityValid = (city, country) => getCities(country).includes(city);


